### ISSUE TITLE
zom and gajim not connecting with each other

### ISSUE THREAD

**Issue by githubboy1** [zom/zom-android-matrix#2]
So i use gajim on linux. 
is it posseble to talk with people using zom? (zom is using jabber protocol right?)

i have tried this on my own for testing.
i have create a zom account on smartphone (testman@nang.zom.im) 
And on Gajim i use TonsOfFun@Jabber.hot-chilli.net 

But its not connecting with each other.

**Comment by githubboy1** [comment]
Hello
can anyone help me?

**Comment by githubboy1** [comment]
Hello?

**Comment by abeluck** [comment]
@githubboy1 sorry about the delay, this is not a channel for support requests.

In the future please email support@zom.im if you have questions about Zom, and you'll get a reply much faster.

To answer your question:

Zom no longer uses the jabber protocol, so no it is not possible to use Gajim to communicate with Zom users.

Zom now uses the matrix protocol, you can find a list of other clients here: https://matrix.org/clients/
