### ISSUE TITLE
zom.im and riot

### ISSUE THREAD

**Issue by githubboy1** [zom/zom-android-matrix#3]
Hello 
so i have this problem also placed by Riot, and they aswer was:
https://github.com/vector-im/riot-web/issues/10588

So my story again:
So i heard that zom.im is using the matrix protocol now.
So i have tried riot desktop messenger (matrix.org) connecting with zom android messenger (:nang.zom.im)
Well thats works, and you can connecting/talking to each other.
But there are few problems:

First there is a verify problem.
i can choose a two way verify verification (doesn't work)
And i can choose for a legacy verify verification.
This last one, is a problem because you must do it again and again when you log in/out with riot. So thats verify verification must me saved somehow..

Second problem, when you log out with riot and log in again, i cant read chat history.
it said: ** Unable to decrypt: The sender's device has not sent us the keys for this message. **
When i click 'Re-request encryption keys' nothing happens..

**Comment by abeluck** [comment]
thanks for the feedback!

1. verification: @turt2live is right, our ios and android apps only support the legacy style verification for now, that is something we hope to change however

2. logging in and out: this was answered in your question over in riot-web. Unfortunately this is how web browsers work. When you log out, all your encryption keys are deleted from the browser. If you want to save them, you must use Riot's key backup functionality.

**Comment by n8fr8** [comment]
You can download your keys and reuplaod them when you log back in again. Overall though, the model is to not logout all of the time. You can exit the browser w/o logging out.

**Comment by ptman** [comment]
there is something called soft logout in matrix these days

**Comment by bleedingcrow** [comment]
@abeluck @n8fr8  will there be something akin to OMEMO-SMP

_Socialist Millionaire Protocol_ 

Challenge Response identity verification

**Comment by abeluck** [comment]
Currently there is no SMP implemented in any matrix client, though it certainly could be.
